SSE 및 알림 기능 구현중
2024-Iris/issuefy-spring pull request #25
Opened 2024-07-06 02:33 UTC by lvalentine6

## 🚀 개요

- 알림 기능
  - 람다 연결을 위한 key를 application.yml에 추가하여 필터를 통과하게 하였습니다.
  - 필터에 CORS 관련 응답을 삭제하여 CORS.config에서 관리할 수 있게 하였습니다.
  - Elasticache에 SSE 커넥션 정보를 저장하여 중복 연결이나 스케일 아웃시 관리하려 하였으나 현재 방법을 고민중입니다.
  - UserNotification, Notification 엔티티를 만들고, 테이블 정보를 수정하였습니다.
  - SseContoller는 SSE 연결 관련 요청을 처리하고, NotificationContoller는 알림 관련 요청을 처리합니다.
  - NotificationContoller는 사용자별 알림 목록과, 알림 읽음 api를 처리합니다.

- 메인 서버에 배포 후 10분마다 람다를 실행시켜 새로운 이슈가 있는지 처리할 예정입니다.

Issue-ID: __issuefy-##__

## 📗 유형

- [x] 새로운 기능 추가
- [x] 버그 수정
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [x] 코드 리팩토링
- [x] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [x] 파일 혹은 폴더명 수정
- [x] 파일 혹은 폴더 삭제

## 🔎 상세 내용

## ✅ Checklist

PR이 다음 요구 사항을 충족하는지 확인하세요.

- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [x] 변경 사항에 대한 테스트를 했습니다.

2024-07-16 14:20 UTC, dokkisan requested changes
이번 pr 코드량이 엄청나네요..!
SSE와 알림 기능을 같이 구현해야 해서 그러셨나봐요..
리뷰도 쉽지 않았지만 로이도 많이 고생하셨을 것 같습니다..! 🥲

남겨드린 코멘트 확인해주시면 감사하겠습니다!! :)

2024-07-16 14:20 UTC, dokkisan commented on src/main/java/site/iris/issuefy/service/NotificationService.java
> +	}
저는 보통 public 메서드를 상단에 위치시키는데요!
메서드 정렬에 대해서도 기준을 만들어보면 좋을 것 같습니다! :)

2024-07-16 14:20 UTC, dokkisan commented on src/main/resources/schema.sql
> +    `push_time`       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
DATETIME의 `NOW()` 와 `CURRENT_TIMESTAMP`의 차이는 무엇인가요?

2024-07-16 14:20 UTC, dokkisan commented on src/test/java/site/iris/issuefy/filter/JwtAuthenticationFilterTest.java
> +		// given
음.. 이 부분은 목 객체를 setUp()으로 빼려고 given을 아래에 적어둔 것 같아요
나중에 테스트도 다시 한 번 검토해봐야겠네요 😂

2024-07-16 14:20 UTC, dokkisan commented on src/main/java/site/iris/issuefy/model/dto/NotificationDto.java
> +	private LocalDateTime localDateTime;
localDateTime은 알림 송신 시간을 나타내는 걸까요?

2024-07-16 14:20 UTC, dokkisan commented on src/main/java/site/iris/issuefy/service/NotificationService.java
> +		for (String repository : updateRepositoryDto.getUpdatedRepositoryIds()) {
repoId를 가져오는 부분 같은데 타입이 String이라 repository로 명명하신 걸까요..??
제가 잘 이해한건지 모르겠네요.. ㅎㅎ

2024-07-16 15:47 UTC, lvalentine6 commented on src/main/java/site/iris/issuefy/config/FilterConfig.java
>  		registrationBean.addUrlPatterns("/api/*");
이전에 /api/* 이던 부분은 삭제하지 않고 추가만 했네요. 반영하겠습니다.!

2024-07-16 16:13 UTC, lvalentine6 commented on src/main/java/site/iris/issuefy/controller/SseController.java
> +	public ResponseEntity<SseEmitter> connect(@RequestAttribute("githubId") String githubId) {
음.. 개발하다보니 그 부분이 좀 혼동이 있었던것 같네요. 통일성을 위해 수정하겠습니다.

2024-07-16 16:16 UTC, lvalentine6 commented on src/main/java/site/iris/issuefy/repository/SubscriptionRepository.java
> +	List<Subscription> findByRepositoryId(Long repositoryId);
네, NotificationService 클래스에 findSubscribeRepositoryUser 메서드에서 사용중입니다. 🥇

2024-07-16 16:27 UTC, lvalentine6 commented on src/main/java/site/iris/issuefy/service/NotificationService.java
> +	}
저는 보통 서비스 플로우 순서대로 정렬을 하는편인데요, 이렇게 하면 다소 복잡한 기능들을 구현할때 적절하게 메서드를 나눠가며 개발할 수 있고, 로그에 나타날때도 플로우순으로 찍히는 장점이 있는것 같아요.

어떤 방식이 더 좋을까요?

2024-07-16 16:30 UTC, lvalentine6 commented on src/main/resources/schema.sql
> +    `push_time`       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
둘다 날짜와 시간을 반환한다는점은 같지만, 미묘하게 다른점은 now()는 주로 쿼리나 함수에서 사용하고,
CURRENT_TIMESTAMP는 컬럼 기본값이나 ON UPDATE 절에서 사용한다고 하네요.

통일성을 위해서 스키마에서는 CURRENT_TIMESTAMP로 수정하겠습니다. 😄

2024-07-16 16:35 UTC, lvalentine6 commented on src/main/java/site/iris/issuefy/model/dto/NotificationDto.java
> +	private LocalDateTime localDateTime;
음.. 알림 생성 시간을 나타내려고 했는데, 변수명을 타입명과 동일하게 해버렸네요.
수정하겠습니다!

2024-07-16 16:44 UTC, lvalentine6 commented on src/main/java/site/iris/issuefy/repository/UserNotificationRepository.java
> +	@Modifying(clearAutomatically = true)
해당 쿼리는 유저가 전체 알림 기능을 누르면 동작하는데요.
리스트로 알림의 id를 전부 받아오다보니, 각 알림 id의 엔티티를 하나씩 가져와서 업데이트 하는것보다 JPQL을 사용하는게 효율적일것 같아서 Query 에너테이션을 사용하게 되었습니다.

Modifying은 Spring Data JPA에게 해당 쿼리가 데이터 수정(INSERT, UPDATE, DELETE)을 수행한다는 것을 알려주고,
(clearAutomatically = true) 은 생성한 엔티티와 DB사이에 동기화가 발생할수 있어 영속성 컨텍스트를 자동으로 초기화 하는것이라고 합니다. 

그런데 생각해보니 이 경우에는 엔티티를 생성하지도 않고 JPQL로 직접 쿼리를 날리고 있어 clearAutomatically = true 이 옵션이 불필요하다는 생각이 드네요. 수정해서 커밋하겠습니다!

2024-07-16 16:48 UTC, lvalentine6 commented on src/main/java/site/iris/issuefy/service/NotificationService.java
> +		for (String repository : updateRepositoryDto.getUpdatedRepositoryIds()) {
밑에 Long repositoryId 가 있어서 별 생각없이 변수명을 만들었는데 오해할만한 변수명이네요. 수정하겠습니다

2024-07-16 16:57 UTC, lvalentine6 commented on src/main/java/site/iris/issuefy/config/RedisConfig.java
> +		return container;
그러네요 수정했습니다 😄

2024-07-17 08:06 UTC, dokkisan approved these changes
고생하셨습니다! 머지하겠습니다 👏👏

2024-07-17 08:06 UTC, merged

2024-07-17 08:07 UTC, lvalentine6 commented
:tada: This issue has been resolved in version 1.13.0 :tada:

The release is available on [GitHub release](https://github.com/2024-Iris/issuefy-spring/releases/tag/v1.13.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: